// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SmartCmdArgs
{
    internal sealed partial class Vsix
    {
        public const string Id = "SmartCmdArgsHDRemix15.f8e3fd0d-1d0f-43c6-a53e-b6bf65fbe854";
        public const string Name = "Smart Command Line Arguments HD Remix VS2017";
        public const string Description = @"A Visual Studio 2017 Extension which aims to provide a better UI to manage your command line arguments.";
        public const string Language = "en-US";
        public const string Version = "3.2.1";
        public const string Author = "Irame & MBulli, tweaks by Kosua20";
        public const string Tags = "Commandline Command Line Arguments cmd project";
    }
}
