// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SmartCmdArgs
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCmdArgsToolWindowPackageString = "33e4dd87-1854-43f2-965b-3f91a1e9fed6";
        public static Guid guidCmdArgsToolWindowPackage = new Guid(guidCmdArgsToolWindowPackageString);

        public const string guidToolWindowString = "45ae1d61-531c-4cf5-82f5-009170691376";
        public static Guid guidToolWindow = new Guid(guidToolWindowString);

        public const string guidVSMenuCmdSetString = "949f3b77-77be-47fb-995e-ba20334e4828";
        public static Guid guidVSMenuCmdSet = new Guid(guidVSMenuCmdSetString);

        public const string guidCmdArgsToolBarCmdSetString = "1d3aeb33-7f70-438a-92b0-31b18f7284d7";
        public static Guid guidCmdArgsToolBarCmdSet = new Guid(guidCmdArgsToolBarCmdSetString);

        public const string guidCustomMonikersString = "456afed8-eeb0-4e2d-bb64-c74a4603a623";
        public static Guid guidCustomMonikers = new Guid(guidCustomMonikersString);

        public const string guidImagesString = "5a350d10-f7c2-409d-9ae6-9bfae3820599";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowCommandId = 0x0100;
        public const int ToolbarAddCommandId = 0x1100;
        public const int ToolbarRemoveCommandId = 0x1101;
        public const int ToolbarMoveUpCommandId = 0x1102;
        public const int ToolbarMoveDownCommandId = 0x1103;
        public const int ToolbarCopyCommandlineCommandId = 0x1104;
        public const int ToolbarAddGroupCommandId = 0x1105;
        public const int ToolbarShowAllProjectsCommandId = 0x1106;
        public const int ToolbarOpenSettingsCommandId = 0x1107;
        public const int ToolbarAddEnvVarId = 0x1108;
        public const int ToolbarCopyEnvVarsForPSCommandId = 0x1109;
        public const int ToolbarCopyEnvVarsForCMDCommandId = 0x110A;
        public const int ToolbarAddWorkDirId = 0x110B;
        public const int ToolbarAddLaunchAppId = 0x110C;
        public const int ToolbarForceHiddenProjectsCommandId = 0x110D;
        public const int TWToolbar = 0x1000;
        public const int TWToolbarGroupAddRemove = 0x1050;
        public const int TWToolbarGroupMove = 0x1051;
        public const int TWToolbarEdit = 0x1052;
        public const int TWToolbarSettings = 0x1053;
        public const int TWToolbarGroupAdd = 0x1054;
        public const int TWToolbarGroupCopyCommandLine = 0x1055;
        public const int TWToolbarGroupCopyEnvVars = 0x1056;
        public const int TWToolbarGroupShowProjects = 0x1057;
        public const int ToolbarAddMenuController = 0x1201;
        public const int ToolbarShowProjectsMenuController = 0x1202;
        public const int ToolbarCopyCommandLineMenuController = 0x1203;
        public const int ToolbarCopyEnvVarsMenu = 0x1204;
        public const int CopyCmdLineIcon = 0x0001;
        public const int bmpVSMenuIcon = 0x0001;
    }
}