// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SmartCmdArgs
{
    internal sealed partial class Vsix
    {
        public const string Id = "SmartCmdArgsHDRemix17.d4a3bf1a-f51e-4532-890b-2b0707510813";
        public const string Name = "Smart Command Line Arguments HD Remix VS2022";
        public const string Description = @"A Visual Studio 2022 Extension which aims to provide a better UI to manage your command line arguments.";
        public const string Language = "en-US";
        public const string Version = "3.2.1";
        public const string Author = "Irame & MBulli, tweaks by Kosua20";
        public const string Tags = "Commandline Command Line Arguments cmd project";
    }
}
